version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        environment:
            - "VIRTUAL_HOST=blog.ip172-18-0-29-bd4oc29io8dg00abf470.direct.labs.play-with-docker.com"
     
  

